FROM node:alpine AS builder

WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine AS serve

# Copy your custom nginx.conf into the container, overwriting the default
COPY nginx-prod/nginx.conf /etc/nginx/nginx.conf

# Copy the static output from the builder stage
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
