version: '3.8'

services:
  api:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://mongo:27017/appdb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"

  mongo:
    image: mongo:7.0
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
