services:
  api:
    build:
      context: ./backend
    volumes:
      - ./backend:/src
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://mongo:27017/appdb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: npm run dev

  mongo:
    image: mongo:7.0
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
