services:
  api:
    build:
      context: ./backend
    volumes:
      - ./backend:/src
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/appdb
    networks:
      - default
      - monitoring
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    ports:
      - "80:5173"
    environment:
      - NODE_ENV=development
    command: npm run dev
    networks:
      - default
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - default
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.dev.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"   
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring    # prometheus net
      - default       
volumes:
  mongo_data:
  grafana_data:
networks:
  default:
    driver: bridge
  monitoring:
    driver: bridge