services:
  api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.prod
    volumes:
      - ./backend:/src
      - goapi_logs:/var/log/goapi/
    environment:
      - MONGO_URI=mongodb://mongo:27017/appdb
    networks:
      - internal-backend
      - monitoring
    expose:
      - "8080"   # internal only API port
      - "9091"   # metrics endpoint

  nginx:
    container_name: nginx
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    networks:
      - default
      - internal-backend
      - monitoring
    volumes:
      - nginx_logs:/var/log/nginx/


  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - internal-backend

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.prod.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    expose:
      - "9090"
      
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    depends_on:
      - nginx
    networks:
      - monitoring
    expose:
      - "9113"      
    command:
      - "-nginx.scrape-uri=http://nginx:80/nginx_status"
  
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # <--- CHANGE THIS
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - loki:/tmp
      - ./monitoring/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/grafana-datasources.yaml:ro
    networks:
      - default
      - monitoring

  loki:
    container_name: loki
    image: grafana/loki
    command: -config.file=/etc/loki/local-config.yaml
    user: root
    volumes:
      - ./monitoring/loki-config.yaml:/etc/loki/local-config.yaml
      - loki:/tmp/loki
    networks:
      - monitoring
    ports:
      - "3100"

  promtail:
    image: grafana/promtail
    volumes:
      - nginx_logs:/var/log/nginx/:ro
      - promtail_positions:/tmp/promtail   
      - goapi_logs:/var/log/goapi/:ro
      - ./monitoring/promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - monitoring

volumes:
  mongo_data:
  grafana_data:
  nginx_logs:
  loki:
  promtail_positions:
  goapi_logs:

networks:
  default:
    driver: bridge

  internal-backend:
    driver: bridge
    internal: true

  monitoring:
    driver: bridge
    internal: true
