services:
  api:
    build:
      context: ./backend
    volumes:
      - ./backend:/src
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/appdb
    networks:
      - default
      - monitoring
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes: [] 
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - default
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - default
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"   
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring    # prometheus net
      - default       
volumes:
  mongo_data:
  grafana_data:
networks:
  default:
    driver: bridge
  monitoring:
    driver: bridge