root = "."

[build]
  cmd = "go build -o tmp/main ./src/cmd"
  bin = "tmp/main"
  full_bin = "tmp/main"

[run]
  cmd = "tmp/main"
  watch_dir = ["./src"]
  include_ext = ["go"]
  exclude_dir = ["vendor", "tmp"]
