FROM golang:alpine AS builder
RUN apk add --no-cache git
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /app/app ./src/cmd/main.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

RUN mkdir -p /var/log/goapi && \
    chown -R appuser:appgroup /var/log/goapi

WORKDIR /app

COPY --from=builder /app/app .

USER appuser

EXPOSE 8080

CMD ["./app"]
