global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["api:9091", "nginx-exporter:9113"]
        labels:
          role: monitoring
          instance: prometheus
